apiVersion: v1
kind: Service
metadata:
  namespace: 
  name: prometheus-service
spec:
  selector: 
    app: prometheus
  ports:
    - name: "prometheus9090"
      protocol: TCP
      port: 9090
      targetPort: 9090

