apiVersion: v1
kind: Service
metadata:
  namespace: farhatemp
  name: promtail-service
spec:
  selector: 
    app: promtail
  ports:
    - name: http
      protocol: TCP
      port: 3101
      targetPort: 3101

