#To be run with [kubectl create -f hpa.yaml] on a Kubernetes Cluster
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
