
# Source: loki-simple-scalable/templates/monitoring/logs-instance.yaml
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: loki-simple-scalable
  namespace: farhatemp
  labels:
    app: loki-simple-scalable
spec:
  clients:
    #TODO: need to support auth here
    - url: <write url>/loki/api/v1/push
    # - url: http://loki-write.default.svc.cluster.local:3100/loki/api/v1/push
      externalLabels:
        cluster: <insert name>

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the LogsInstance CR
  podLogsNamespaceSelector: { }

  # podLogsSelector:
  #   matchLabels:
  #     instance: primary
---
