apiVersion: apps/v1
kind: Deployment 
metadata:
  name: loki-ss-read
  labels:
    app: loki-simple-scalable
    service: read
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  targetModule: "read"
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  serviceName: loki-ss-read
  revisionHistoryLimit: 10

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  selector:
    matchLabels:
      app: loki-simple-scalable
      service: read
  template:
    metadata:
      annotations:
        checksum/config: <xyz>
      labels:
        app: loki-simple-scalable
        service: read
    spec:
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      containers:
        - name: loki-ss-read
          image:  grafana/loki
          imagePullPolicy: Always
          commands: 
          args: 
            - '-config.file'
            - '/etc/loki/local-config.yml'
            - '-target=read'
          ports:
            - name: read-port
              containerPort: 3105
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            httpGet:
              path: /ready
              port: 3105
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: loki-ss-storage
              mountPath: /tmp
            - name: local-config
              mountPath: /etc/loki
      volumes:
        - name: loki-ss-storage
          persistentVolumeClaim:
            claimName: loki-ss-storage
        - name: tmp
          emptyDir: {}
        - name: local-config
          configMap:
            name: local-config
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: loki-ss-read
  labels:
    app: loki-simple-scalable
    service: read
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: read-port
      port: 3105
      targetPort: read-port
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
    - name: http-memberlist
      port: 7946
      targetPort: http-memberlist 
      protocol: TCP
  selector:
    service: read
---