# Loki Memberlist Service
apiVersion: v1
kind: Service
metadata:
  name: loki-ss-memberlist
  labels:
    app: loki-simple-scalable
    service: memberlist
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    service: memberlist
